version: 0.2
phases:
  pre_build:
    commands:
      - echo pre build step
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo COMMIT_HASH
      - echo pre build over
      # - command
  build:
    commands:
      - echo Build started on `date`
      - echo starting maven build
      - cd $CODEBUILD_SRC_DIR
      - mvn clean install
      - echo Building the Docker image.
      - docker build --build-arg JAR_FILE=target/*.jar -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
      # docker build --build-arg JAR_FILE=target/*.jar -t arorajatin08/demoapp:${COMMIT_HASH} .
      # - command
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
